# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: K. Leo Pullin
  avatar: _Trop92.jpg
  gravatar: # Email MD5 hash
  description: "My Bloc.io Ruby on Rails Web Developer Journey" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Developer, Microscopist, Geologist, Artist, and human being.</h1>
  header_text_feature_image:
  footer_text: >
  Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "kleopullin@email.arizona.edu"
  linkedin:  https://www.linkedin.com/in/kleopullin
  github: "KleoP"
  twitter: "resolvingdust"
  wordpress: http://stillcomingashore.com/
  instagram: "kleopullin"
  stack_exchange:  http://stackexchange.com/users/6884004/kleopullin
  dribbble: "resolvingdust"
  facebook: "kleopullinReshoot"
  behance:
  bitbucket:
  flickr:
  google_plus:
  pinterest:
  reddit:
  soundcloud:
  steam:
  tumblr:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]